spring.application.name=investech
server.port=${SERVER_PORT:8081}

# Banco de Dados
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:investech}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:*Gui1709*06}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver